AllCops:
  Exclude:
    - http_stub.gemspec
    - Rakefile
    - spec/**/*
    - vendor/**/*
  TargetRubyVersion: 2.2

# double quotes preferred, except in require
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# appropriate hash formatting varies wildly
Style/MultilineMethodCallBraceLayout:
  Enabled: false
Style/AlignHash:
  Enabled: false

# tolerate names that are not predicates
Style/PredicateName:
  NameWhitelist:
    - has_started!

# aids readability
Style/RedundantSelf:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/Alias:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/IndentAssignment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - lib/http_stub/server/application/request_support.rb
    - lib/http_stub/server/application/response_support.rb
    - lib/http_stub/server/application/routes/*.rb
Performance/RedundantMerge:
  Exclude:
    - lib/http_stub/server/daemon.rb

# sufficient length for modern screens
Metrics/LineLength:
  Max: 120

# {} distinguishes delimiters from method calls
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '{}'
    '%w': '{}'

# self-documentation preferred
Style/Documentation:
  Enabled: false

# conditionals should contain statements
Style/EmptyElse:
  EnforcedStyle: empty

# rare situations where readability is preferred over metrics aspirations
Metrics/MethodLength:
  Exclude:
    - lib/http_stub/server/application/routes/*.rb
Metrics/BlockLength:
  Exclude:
    - examples/*.rb
    - lib/http_stub/server/application/routes/*.rb
Metrics/AbcSize:
  Exclude:
    - lib/http_stub/server/application/routes/*.rb
    - lib/http_stub/server/stub/response/base.rb
