dist: xenial
language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
services:
  - xvfb
addons:
  firefox: 68.0
before_install:
  - gem update --system
  - gem --version
  - gem install bundler rake
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: rake commit
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache: bundler
notifications:
  email:
    on_success: change
    on_failure: always
