language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
addons:
  firefox: 53.0
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem update --system
  - gem --version
  - gem install bundler rake
script: rake commit
cache: bundler
notifications:
  email:
    on_success: change
    on_failure: always
